apiVersion: apps/v1
kind: Deployment
metadata: 
 name: mysql-deployment
 namespace: mysql
 labels: 
  app: mysql

spec:
  replicas: 1
  selector: 
   matchLabels:
     app: mysql
  template: 
   metadata:
     labels: 
      app: mysql
   spec: 
    containers:
     - name: mysql-container
       image: mysql:latest
       ports: 
        - containerPort: 3306
       env:
         - name: MYSQL_ROOT_PASSWORD
           valueFrom:
            secretKeyRef:
             name: mysql-secret
             key: MYSQL_ROOT_PASSWORD
         - name: MYSQL_DATABASE
           valueFrom:
            configMapKeyRef:
             name: mysql-configmap
             key: MYSQL_DATABASE
       volumeMounts:
        - name : mysql-dockercontainer-storage
          mountPath: /var/lib/mysql
    volumes: 
     - name: mysql-dockercontainer-storage
       persistentVolumeClaim: 
        claimName: mysql-pvc

